package org.hyperion.hypercon;

import org.hyperion.hypercon.spec.*;

import java.awt.*;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Locale;
import java.util.Vector;
import org.hyperion.hypercon.*;
/**
 * The full configuration of Hyperion with sub-items for device, color, grabber-v4l2 and miscelanuous items.
 */
public class LedString {
	/** The configuration of the output device */
	public final DeviceConfig mDeviceConfig = new DeviceConfig();

	/** THe configuration of the 'physical' led frame */
	public final LedFrameConstruction mLedFrameConfig = new LedFrameConstruction();
	
	/** The configuration of the image processing */
	public final ImageProcessConfig mProcessConfig = new ImageProcessConfig();

	/** The configuration of the BlackBorder processing */
	public final BlackBorderConfig mBlackBorderConfig = new BlackBorderConfig();
	
	/** The color adjustment configuration */
	public final ColorConfig mColorConfig = new ColorConfig();
	
	/** The miscellaneous configuration (bootsequence, blackborder detector, etc) */
	public final MiscConfig mMiscConfig = new MiscConfig();

	/** The configuration for the grabber-v4l2" */
	public final Grabberv4l2Config mGrabberv4l2Config = new Grabberv4l2Config();

	/** The translation of the led frame construction and image processing to individual led configuration */
	public Vector<Led> leds;
	
	/**
	 * Writes the configuration to the given file
	 * 
	 * @param mFilename The absolute filename
	 * 
	 * @throws IOException If unable to write the given file
	 */
	public void saveConfigFile(String mFilename) throws IOException {
		
		try (FileWriter fw = new FileWriter(mFilename)) {
			fw.write("// Automatically generated configuration file for 'Hyperion daemon'\n"); //$NON-NLS-1$
			fw.write("// Generated by: HyperCon (The Hyperion deamon configuration file builder)\n" //$NON-NLS-1$
			+ "// "+ "Created with HyperCon " + (Main.versionStr) + " " +(Main.DateStr) + "\n");
			fw.write("\n"); //$NON-NLS-1$
			fw.write("{\n"); //$NON-NLS-1$
			
			String deviceJson = mDeviceConfig.toJsonString();
			fw.write(deviceJson + ",\n\n"); //$NON-NLS-1$
			
			String colorJson = mColorConfig.toJsonString();
			fw.write(colorJson + ",\n\n"); //$NON-NLS-1$

			JsonStringBuffer jsonBuf = new JsonStringBuffer(1);

//			mProcessConfig.appendTo(jsonBuf);
			mBlackBorderConfig.appendTo(jsonBuf);
			
			jsonBuf.newLine();
			
			mMiscConfig.appendTo(jsonBuf);
			
			jsonBuf.newLine();

			mGrabberv4l2Config.appendTo(jsonBuf);

			jsonBuf.newLine();

			ledsAppendTo(jsonBuf);

			jsonBuf.newLine();

			jsonBuf.addValue("endOfJson", "endOfJson", true); //$NON-NLS-1$ //$NON-NLS-2$
			
			fw.write(jsonBuf.toString());
			
			fw.write("}\n"); //$NON-NLS-1$
		} catch (IOException e) {
			throw e;
		}
	}
	
	void ledsAppendTo(JsonStringBuffer pJsonBuf) {
		String ledComment = 
				" The configuration for each individual led. This contains the specification of the area \n" +  //$NON-NLS-1$
				" averaged of an input image for each led to determine its color. Each item in the list \n" + //$NON-NLS-1$
				" contains the following fields:\n" + //$NON-NLS-1$
				" * index: The index of the led. This determines its location in the string of leds; zero \n" + //$NON-NLS-1$
				"          being the first led.\n" + //$NON-NLS-1$
				" * hscan: The fractional part of the image along the horizontal used for the averaging \n" + //$NON-NLS-1$
				"          (minimum and maximum inclusive)\n" + //$NON-NLS-1$
				" * vscan: The fractional part of the image along the vertical used for the averaging \n" + //$NON-NLS-1$
				"          (minimum and maximum inclusive)\n"; //$NON-NLS-1$
		pJsonBuf.writeComment(ledComment);
		
		pJsonBuf.startArray("leds"); //$NON-NLS-1$
		for (Led led : leds)
		{
			pJsonBuf.startObject(""); //$NON-NLS-1$
			pJsonBuf.addValue("index", led.mLedSeqNr, false); //$NON-NLS-1$
			pJsonBuf.addRawValue("hscan", String.format(Locale.ENGLISH, "{ %1$cminimum%1$c : %2$.4f, %1$cmaximum%1$c : %3$.4f }", '"', led.mImageRectangle.getMinX(), led.mImageRectangle.getMaxX()), false); //$NON-NLS-1$ //$NON-NLS-2$
			pJsonBuf.addRawValue("vscan", String.format(Locale.ENGLISH, "{ %1$cminimum%1$c : %2$.4f, %1$cmaximum%1$c : %3$.4f }", '"', led.mImageRectangle.getMinY(), led.mImageRectangle.getMaxY()), true); //$NON-NLS-1$ //$NON-NLS-2$
			pJsonBuf.stopObject(led.equals(leds.get(leds.size()-1)));
		}
		pJsonBuf.stopArray(false);
	}

	public static void main(String[] pArgs) {

		LedString ls = new LedString();
		Led led = new Led();
		led.mImageRectangle = new Rectangle(1,1,1,1);
		led.mLedSeqNr = 0;
		led.mLocation = new Point(1,2);
		led.mSide = BorderSide.bottom;
		ls.leds = new Vector<Led>();
		ls.leds.add(led);
		try {
			ls.saveConfigFile("testclassconfig.json"); //$NON-NLS-1$

		}catch (Exception e){
			e.printStackTrace();
		}
	}
}
